import test from 'node:test';
import assert from 'node:assert/strict';
import { discountGuidance, discountEscalationText, supportsDiscountGuide } from '../lib/discount-guide.ts';
import { seedEntries } from '../lib/seed.ts';
import { updateDiscountPolicy, discountPolicyId } from '../lib/discount-policy.ts';

test('off-by-one correction preserves previous rule and rejects unexpected edits',()=>{
 const previous={...seedEntries[0],id:'discount-policy-2026-08-31',status:'Active',decision:'First-time purchasers (0 previous orders) → 5% off. Customers with 1–10 previous orders → no discount. Customers with more than 10 previous orders → 10% off.',reasoning:'Previous reasoning',exception:''};
 const state={entries:[previous],cases:[],notices:[]};
 const next=updateDiscountPolicy(state,123);
 assert.equal(previous.status,'Active');
 assert.equal(next.entries[0].decision,previous.decision);
 assert.equal(next.entries[0].status,'Superseded');
 assert.equal(next.entries[1].supersedesId,previous.id);
 assert.match(next.entries[1].decision,/10 or more/);
 assert.match(next.entries[1].reasoning,/second purchase/);
 assert.match(next.entries[1].reasoning,/contribution/);
 assert.ok(supportsDiscountGuide(next.entries[1]));
 assert.equal(updateDiscountPolicy(next),next);
 previous.decision='Separately revised policy';
 assert.equal(updateDiscountPolicy(state),state);
});
test('guide applies only to the supported current additional-discount rule',()=>{const rule=updateDiscountPolicy({entries:seedEntries,cases:[],notices:[]}).entries.find(e=>e.id===discountPolicyId);assert.ok(supportsDiscountGuide(rule));for(const changed of [{...rule,status:'Superseded'},{...rule,id:'revision'},{...rule,decision:'New policy'},{...rule,exception:'Different exception'},undefined,seedEntries.find(e=>e.id==='1'),seedEntries.find(e=>e.id==='4')])assert.equal(supportsDiscountGuide(changed),false);});
test('zero prior orders receives five percent',()=>{assert.equal(discountGuidance('0').title,'Offer 5% off');assert.match(discountGuidance('00').context,/Previous orders: 0/);});
test('one through nine receive no discount',()=>{for(const n of ['1','5','9']){assert.equal(discountGuidance(n).title,'No discount');assert.match(discountGuidance(n).context,/no discount/);}});
test('ten or more previous orders receives ten percent',()=>{for(const n of ['10','11','12','100']){const result=discountGuidance(n);assert.equal(result.title,'Offer 10% off');assert.match(result.context,/10% off/);}});
test('unknown is explicit and invalid input never yields policy guidance',()=>{assert.match(discountGuidance('unknown').context,/unknown \(not verified\)/);for(const n of ['',' ','-1','1.5','1e2','ten','Infinity','9007199254740992'])assert.equal(discountGuidance(n),null);});
test('escalation preserves situation and includes the supplied count and policy',()=>{const result=discountEscalationText('customer wants additional discount.','12');assert.ok(result.startsWith('customer wants additional discount.'));assert.match(result,/Previous orders: 12 \(team-provided\)/);assert.match(result,/10% off/);assert.match(discountEscalationText('original','10'),/10% off/);assert.equal(discountEscalationText('original',''),'original');});
test('policy update preserves history and other data and runs only once',()=>{const state={entries:structuredClone(seedEntries),cases:[{id:'preserve'}],notices:[{id:'preserve'}]};const next=updateDiscountPolicy(state,123);assert.equal(state.entries[0].status,'Active');assert.equal(next.entries[0].status,'Superseded');assert.equal(next.entries[0].replacementId,discountPolicyId);assert.equal(next.entries.at(-1).supersedesId,'1');assert.equal(next.entries.at(-1).createdAt,123);assert.deepEqual(next.entries.slice(1,-1),state.entries.slice(1));assert.deepEqual(next.cases,state.cases);assert.deepEqual(next.notices,state.notices);assert.equal(updateDiscountPolicy(next),next);});
test('policy update does not overwrite a separately revised rule',()=>{const state={entries:structuredClone(seedEntries),cases:[],notices:[]};state.entries[0].decision='Another approved rule';assert.equal(updateDiscountPolicy(state),state);});
test('previous deployed policy is superseded without losing the older history',()=>{const state={entries:structuredClone(seedEntries),cases:[],notices:[]};const original=state.entries[0];original.status='Superseded';original.replacementId='discount-policy-2026-08-30';const previous={...original,id:original.replacementId,status:'Active',supersedesId:'1',replacementId:undefined,decision:'First-time purchasers (0 previous orders) → 5% off. Customers with more than 10 previous orders → 10% off.'};state.entries.push(previous);const next=updateDiscountPolicy(state,123);assert.deepEqual(next.entries[0],original);assert.equal(next.entries.at(-2).status,'Superseded');assert.equal(next.entries.at(-2).replacementId,discountPolicyId);assert.equal(next.entries.at(-1).supersedesId,previous.id);assert.ok(supportsDiscountGuide(next.entries.at(-1)));assert.equal(updateDiscountPolicy(next),next);previous.status='Superseded';assert.equal(updateDiscountPolicy(state),state);});
