'use client';

import { useCallback, useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { BookOpen, Search, ShieldCheck, ArrowUpRight, Inbox, Clock, ChevronDown, LockKeyhole, CircleAlert, Check, Library } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { DiscountFollowUp } from '@/components/discount-follow-up';
import { DamageFollowUp } from '@/components/damage-follow-up';
import { supportsDamageGuide, damageEscalationText } from '@/lib/damage-guide';
import { supportsDiscountGuide, discountEscalationText } from '@/lib/discount-guide';
import { Input } from '@/components/ui/input';
import { ReportRuleForm, RuleFeedbackCase } from '@/components/rule-feedback';
import { RoutingDemo } from '@/components/routing-demo';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { categories, currentRule, people, publicRisk, queue, search, type Entry, type Role, type Situation } from '@/lib/domain';

type Snapshot={entries:Entry[];cases:Situation[];role:Role;services?:{storage?:string}};
type View='search'|'browse'|'submitted'|'queue'|'manage';
type Draft={kind:'answer'|'review'|'promote'|'replace';item?:Situation;entry?:Entry};
const initial:Snapshot={entries:[],cases:[],role:'team'};
const age=(time:number)=>{const mins=Math.max(0,Math.floor((Date.now()-time)/60000));return mins<60?`${mins}m waiting`:mins<1440?`${Math.floor(mins/60)}h ${mins%60}m waiting`:`${Math.floor(mins/1440)}d waiting`;};
const date=(time:number)=>new Date(time).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});

async function request<T>(path:string,body?:unknown,method='POST'):Promise<T>{const response=await fetch(path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},...(body!==undefined?{body:JSON.stringify(body)}:{})});const data=await response.json() as T&{error?:string};if(!response.ok)throw new Error(data.error||'Could not save. Please retry.');return data;}

function PrecedentCard({entry,entries,expanded=false,possible=false,onEscalate,onReplace,onReport,followUp}:{entry:Entry;followUp?:ReactNode;entries:Entry[];expanded?:boolean;possible?:boolean;onEscalate?:(entry:Entry)=>void;onReplace?:(entry:Entry)=>void;onReport?:(entry:Entry)=>void}){
 const [open,setOpen]=useState(expanded);
 const old=entries.find(e=>e.id===entry.supersedesId);
 return <article className={`precedent-card ${open?'expanded':''}`} id={`precedent-${entry.id}`}>
  <div className="card-meta"><span>{entry.category}{entry.seed?' · Seed':''}</span><span className={possible?'status-pill amber':'status-pill'}>{possible?'Possible match':entry.status}</span></div>
  <button className="card-toggle" type="button" aria-expanded={open} onClick={()=>setOpen(!open)}><h3>{entry.title}</h3><ChevronDown className={open?'turned':''} size={19}/></button>
  {!open&&<p className="situation-copy">{entry.situation}</p>}
  {entry.founderOnly&&<p className="notice amber"><CircleAlert size={15}/>Founder decision required · High priority, no timed CoS fallback</p>}
  {open&&<><div className="rule-box"><h4>THE RULE</h4><p>{entry.decision}</p></div><details className="rule-details"><summary>Reasoning, exceptions &amp; history</summary><p className="situation-copy">{entry.situation}</p><div className="card-columns"><div><h4>WHY THIS EXISTS</h4><p>{entry.reasoning||'Not recorded'}</p></div><div><h4>THE EXCEPTION</h4><p>{entry.exception||'None recorded'}</p></div></div>
  {old&&<details className="old-rule"><summary>Previously: {old.title} · Superseded</summary><p>{old.decision}</p><p><strong>Why it changed:</strong> {entry.changeReason||'Not recorded'}</p><p>Replaced by the Active rule above. Do not use this old rule.</p></details>}</details>
  {followUp}<div className="card-bottom">{onEscalate&&<Button className="escalate-action" variant="ghost" onClick={()=>onEscalate(entry)}>{entry.founderOnly?'Ask founder':'This doesn’t apply—ask founder'}<ArrowUpRight size={14}/></Button>}{onReport&&entry.status==='Active'&&<Button className="report-action" variant="outline" onClick={()=>onReport(entry)}>This decision didn’t work</Button>}{onReplace&&<Button variant="outline" onClick={()=>onReplace(entry)}>Replace this rule</Button>}</div></>}
 </article>;
}

function DecisionForm({draft,role,entries,onSave,onClose}:{draft:Draft;role:Role;entries:Entry[];onSave:(action:Record<string,unknown>)=>Promise<void>;onClose:()=>void}){
 const original=draft.item?.answer||draft.entry;
 const [decision,setDecision]=useState(original?.decision||'');
 const [reasoning,setReasoning]=useState(original?.reasoning||'');
 const [exception,setException]=useState(original?.exception||'');
 const [publish,setPublish]=useState(draft.kind==='replace'||draft.kind==='promote'?'yes':'');
 const [category,setCategory]=useState(draft.entry?.category||'');
 const [oldId,setOldId]=useState(draft.entry?.id||'');
 const [changeReason,setChangeReason]=useState('');
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const locked=useRef(false);const actionId=useRef(crypto.randomUUID());
 async function submit(e:FormEvent){e.preventDefault();if(locked.current)return;locked.current=true;setBusy(true);setError('');try{await onSave({kind:draft.kind,id:actionId.current,caseId:draft.item?.id,decision,reasoning,exception,savePrecedent:role==='founder'&&publish==='yes',category,supersedesId:publish==='yes'?oldId:undefined,changeReason});}catch(e){setError((e as Error).message);}finally{locked.current=false;setBusy(false);}}
 return <section className="edit-panel"><div className="section-heading"><h2>{draft.kind==='review'?'Review the CoS decision':draft.kind==='replace'?'Replace an existing rule':draft.kind==='promote'?'Make this a precedent':'Record a decision'}</h2><Button variant="ghost" disabled={busy} onClick={onClose}>Close</Button></div>
  <p className="context-text">{draft.item?.situation||draft.entry?.situation}</p>
  {draft.kind==='review'&&<p className="notice">The team can already act on the CoS answer. It remains recorded as a one-off; your approved wording governs future cases.</p>}
  {draft.kind==='replace'&&<p className="notice">The old rule will remain attached to its replacement. A reason for the change is required.</p>}
  <form onSubmit={submit} className="fields"><label>Decision<Textarea required value={decision} onChange={e=>setDecision(e.target.value)}/></label><label>Reasoning<Textarea required value={reasoning} onChange={e=>setReasoning(e.target.value)}/></label><label>Exception <small>(optional)</small><Textarea value={exception} onChange={e=>setException(e.target.value)}/></label>
  {role==='founder'&&<label>Future use<NativeSelect required value={publish} onChange={e=>setPublish(e.target.value)} disabled={draft.kind==='replace'||draft.kind==='promote'}><NativeSelectOption value="">Choose one</NativeSelectOption><NativeSelectOption value="yes">Save as precedent for future search</NativeSelectOption><NativeSelectOption value="no">One-off only</NativeSelectOption></NativeSelect></label>}
  {role==='cos'&&<p className="notice">This will be an immediately actionable one-off, awaiting founder review.</p>}
  {publish==='yes'&&role==='founder'&&<><label>Category<NativeSelect required value={category} onChange={e=>setCategory(e.target.value)}><NativeSelectOption value="">Choose category</NativeSelectOption>{categories.map(c=><NativeSelectOption key={c}>{c}</NativeSelectOption>)}</NativeSelect></label>
  <label>Replace an existing rule <small>(optional)</small><NativeSelect value={oldId} onChange={e=>setOldId(e.target.value)} disabled={draft.kind==='replace'}><NativeSelectOption value="">Do not replace a rule</NativeSelectOption>{entries.filter(e=>e.status==='Active').map(e=><NativeSelectOption key={e.id} value={e.id}>{e.title}</NativeSelectOption>)}</NativeSelect></label>{oldId&&<label>Why is the rule changing?<Textarea required value={changeReason} onChange={e=>setChangeReason(e.target.value)}/></label>}</>}
  {error&&<p className="error" role="alert">{error}</p>}<Button type="submit" disabled={busy}>{busy?'Saving…':error?'Retry':draft.kind==='review'?publish==='yes'?'Approve for future use':'Keep as one-off':'Save decision'}</Button></form>
 </section>;
}

export default function PrecedentApp(){
 const [discountOrders,setDiscountOrders]=useState('');
 const [damageAnswers,setDamageAnswers]=useState<string[]>([]);
 const [report,setReport]=useState<Entry|null>(null);
 const [data,setData]=useState<Snapshot>(initial);const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState('');const [view,setView]=useState<View>('search');
 const [text,setText]=useState('');const [query,setQuery]=useState<string|null>(null);const [queryError,setQueryError]=useState('');const [category,setCategory]=useState('All categories');const [libraryQuery,setLibraryQuery]=useState('');
 const [access,setAccess]=useState(false);const [accessRole,setAccessRole]=useState('founder');const [pin,setPin]=useState('');const [accessError,setAccessError]=useState('');const [accessBusy,setAccessBusy]=useState(false);
 const [escalation,setEscalation]=useState<{text:string;sourceId?:string;id:string}|null>(null);const [submitter,setSubmitter]=useState('');const [priority,setPriority]=useState('');const [submitError,setSubmitError]=useState('');const [saving,setSaving]=useState(false);const submitLock=useRef(false);
 const [draft,setDraft]=useState<Draft|null>(null);const [notice,setNotice]=useState('');const [expandedCase,setExpandedCase]=useState<string|null>(null);
 const authVersion=useRef(0);
 const refresh=useCallback(async()=>{const version=authVersion.current;try{const result=await request<Snapshot>('/api/state',undefined,'GET');if(version!==authVersion.current)return;setData(result);setLoadError('');}catch{if(version===authVersion.current)setLoadError("Couldn't load precedents — try again");}finally{setLoading(false);}},[]);
 useEffect(()=>{refresh();const timer=setInterval(refresh,15000);return ()=>clearInterval(timer);},[refresh]);
 function go(next:View){setView(next);setDraft(null);setNotice('');}
 function escalate(entry?:Entry){const source=entry||matches[0]?.entry;const current=query===text.trim()&&source?.id===matches[0]?.entry.id;const guided=current&&supportsDiscountGuide(source);const damaged=current&&supportsDamageGuide(source);const situation=text.trim()||entry?.situation||'';setEscalation({text:guided?discountEscalationText(situation,discountOrders):damaged?damageEscalationText(situation,damageAnswers):situation,sourceId:entry?.id||(guided||damaged?source?.id:undefined),id:crypto.randomUUID()});setSubmitter('');setPriority('');setSubmitError('');}
 async function saveEscalation(e:FormEvent){e.preventDefault();if(!escalation||submitLock.current)return;submitLock.current=true;setSaving(true);setSubmitError('');try{const response=await request<{case?:Situation;warning?:string}>('/api/state',{kind:'escalate',id:escalation.id,situation:escalation.text,sourceId:escalation.sourceId,submitter,priority});setEscalation(null);setView('submitted');setExpandedCase(response.case?.id||null);setNotice(response.warning||'Saved.');await refresh();}catch(e){setSubmitError((e as Error).message);}finally{submitLock.current=false;setSaving(false);}}
 async function saveReport(action:Record<string,unknown>){try{const response=await request<{warning?:string}>('/api/state',action);setReport(null);setView('submitted');setNotice(response.warning||'Report saved for founder review.');await refresh();}catch(e){await refresh();throw e;}}
 async function saveDecision(action:Record<string,unknown>){try{const response=await request<{warning?:string}>('/api/state',action);setNotice(response.warning||'Saved.');setDraft(null);await refresh();}catch(e){await refresh();throw e;}}
 async function unlock(e:FormEvent){e.preventDefault();if(accessBusy)return;setAccessBusy(true);setAccessError('');try{const result=await request<{role:Role}>('/api/auth',{role:accessRole,pin});authVersion.current+=1;setData(previous=>({...previous,role:result.role}));setPin('');setAccess(false);setView('queue');await refresh();}catch(e){setAccessError((e as Error).message);}finally{setAccessBusy(false);}}
 async function backToTeam(){if(accessBusy)return;if(draft&&!window.confirm('Return to team view? Any unsaved decision changes will be discarded.'))return;setAccessBusy(true);setAccessError('');try{await request<{role:Role}>('/api/auth',undefined,'DELETE');authVersion.current+=1;setData(previous=>({...previous,role:'team'}));setView('search');setDraft(null);setAccess(false);setPin('');setNotice('You’re back in team view. Founder and CoS actions are locked.');await refresh();}catch(e){setNotice((e as Error).message);}finally{setAccessBusy(false);}}
 function switchRole(role:Role){if(accessBusy)return;if(role==='team'){if(data.role!=='team'){void backToTeam();return;}setAccess(false);setPin('');setAccessError('');return;}if(role===data.role){setAccess(false);setPin('');return;}if(draft&&!window.confirm('Switch views? Any unsaved decision changes will be discarded.'))return;setDraft(null);setAccessRole(role);setPin('');setAccessError('');setAccess(true);}
 const matches=query?search(data.entries,query):[];const active=data.entries.filter(e=>e.status==='Active');const founderOnly=!!escalation&&(publicRisk(escalation.text)||!!data.entries.find(e=>e.id===escalation.sourceId)?.founderOnly);
 const library=active.filter(e=>(category==='All categories'||e.category===category)&&(!libraryQuery||`${e.title} ${e.situation}`.toLowerCase().includes(libraryQuery.toLowerCase())));
 const queued=queue(data.cases,data.role);const isStaff=data.role!=='team';
 return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-icon"><BookOpen size={22}/></span><div><strong>SCENTIRA</strong><span>Decision Precedent Tool</span></div></div><div className="access-actions"><span className="role-description">View as</span><div className="role-toggle" role="group" aria-label="Switch view">{(['team','founder','cos'] as const).map(role=><Button key={role} variant="ghost" className={`role-choice${data.role===role?' is-active':''}`} aria-pressed={data.role===role} aria-label={role==='cos'?'Chief of staff view':`${role} view`} disabled={accessBusy||loading} onClick={()=>switchRole(role)}>{role==='team'?'Team':role==='founder'?'Founder':'CoS'}</Button>)}</div></div></header>
 <nav className="tabs" aria-label="Main navigation"><Button aria-current={view==='search'?'page':undefined} variant={view==='search'?'secondary':'ghost'} onClick={()=>go('search')}><Search size={15}/>Find a precedent</Button><Button aria-current={view==='submitted'?'page':undefined} variant={view==='submitted'?'secondary':'ghost'} onClick={()=>go('submitted')}><Inbox size={15}/>Submitted situations{data.cases.length>0&&<span className="count">{data.cases.length}</span>}</Button>{isStaff&&<Button aria-current={view==='queue'?'page':undefined} variant={view==='queue'?'secondary':'ghost'} onClick={()=>go('queue')}><Clock size={15}/>Decision queue <span className="count">{queued.length}</span></Button>}{data.role==='founder'&&<Button aria-current={view==='manage'?'page':undefined} variant={view==='manage'?'secondary':'ghost'} onClick={()=>go('manage')}><Library size={15}/>Manage precedents</Button>}</nav>
 <main className="workspace">
 {access&&<section className="edit-panel"><div className="section-heading"><h2>Unlock {accessRole==='founder'?'founder':'chief of staff'} view</h2><Button variant="ghost" disabled={accessBusy} onClick={()=>{setAccess(false);setPin('');}}>Close</Button></div><p className="muted">Enter this role’s PIN to switch views. Your current view stays active until it’s accepted.</p><form className="access-form" onSubmit={unlock}><label>Shared PIN<Input type="password" required autoComplete="current-password" inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value)}/></label><Button type="submit" disabled={accessBusy}>{accessBusy?'Checking…':'Unlock'}</Button></form>{accessError&&<p className="error" role="alert">{accessError}</p>}</section>}
 {notice&&<p className="notice" role="status">{notice}<Button variant="ghost" onClick={()=>setNotice('')}>Dismiss</Button></p>}
 {loadError&&<div className="error" role="alert">{loadError}<Button variant="outline" onClick={refresh}>Retry</Button><p>Any previous results may be out of date. Your entered text is preserved.</p></div>}
 {view==='search'&&<><h1>What are you stuck on?</h1><p className="intro">Find a past decision. Know your next step.</p>
 <form className="search-panel" onSubmit={e=>{e.preventDefault();if(!text.trim()){setQueryError('Describe the situation first.');return;}setQueryError('');setDiscountOrders('');setDamageAnswers([]);setQuery(text.trim());}}><label htmlFor="situation">Describe the situation</label><Textarea id="situation" value={text} onChange={e=>{setText(e.target.value);setDiscountOrders('');setDamageAnswers([]);}} placeholder="For example, a customer received a damaged perfume but has no unboxing video…"/><div className="search-actions"><small>Founder’s words, not AI advice. Search isn’t saved.</small><Button type="submit" disabled={loading||!!loadError}><Search size={16}/>Find a decision</Button></div>{queryError&&<p className="error" role="alert">{queryError}</p>}</form>
 <Button variant="link" className="browse-link" onClick={()=>go('browse')}><Library size={14}/>Browse by category<ArrowUpRight size={14}/></Button>
 {!loadError&&<section className="library-section"><div className="section-heading"><h2>{query===null?'From your precedent library':matches.length?'Closest precedents':'Nothing like this has come up before'}</h2><span>{active.length} ACTIVE RULES · 3 CATEGORIES</span></div>{loading?<p className="muted" role="status">Loading the shared library…</p>:query===null?active.slice(0,3).map((entry,i)=><PrecedentCard key={`initial-${entry.id}`} entry={entry} entries={data.entries} expanded={i===0} onEscalate={escalate} onReport={setReport}/>):matches.map(({entry,possible},i)=><PrecedentCard key={`${query}-${entry.id}`} followUp={i===0&&query===text.trim()?(supportsDiscountGuide(entry)?<DiscountFollowUp value={discountOrders} onChange={setDiscountOrders}/>:supportsDamageGuide(entry)?<DamageFollowUp answers={damageAnswers} onChange={setDamageAnswers}/>:undefined):undefined} entry={entry} entries={data.entries} expanded={i===0} possible={possible} onEscalate={escalate} onReport={setReport}/>)}{query!==null&&<div className="escalation-callout"><div><strong>{matches.length?'Not the right fit?':'New situation. Human judgment.'}</strong><p>Carry your description forward and ask for a decision.</p></div><Button variant={matches.length?'outline':'default'} onClick={()=>escalate()} disabled={loading}>Escalate<ArrowUpRight size={14}/></Button></div>}</section>}</>}
 {(view==='browse'||view==='manage')&&<><div className="eyebrow">THE SHARED LIBRARY</div><h1>{view==='manage'?'Manage precedents':'Browse by category'}</h1><p className="intro">Current rules first. Previous rules stay attached so changes make sense.</p><div className="filters"><label>Category<NativeSelect value={category} onChange={e=>setCategory(e.target.value)}><NativeSelectOption>All categories</NativeSelectOption>{categories.map(c=><NativeSelectOption key={c}>{c}</NativeSelectOption>)}</NativeSelect></label><label>Find in library<Input value={libraryQuery} onChange={e=>setLibraryQuery(e.target.value)} placeholder="Title or situation…"/></label></div>{!loadError&&library.map(entry=><PrecedentCard key={entry.id} entry={entry} entries={data.entries} onEscalate={escalate} onReport={setReport} onReplace={view==='manage'&&data.role==='founder'?entry=>setDraft({kind:'replace',entry}):undefined}/>)}{!loading&&!loadError&&!library.length&&<p className="empty">No precedents in this selection.</p>}</>}
 {(view==='submitted'||view==='queue')&&<><div className="eyebrow">{view==='queue'?'DECISIONS WAITING ON YOU':'ONE SHARED RECORD'}</div><h1>{view==='queue'?'Decision queue':'Submitted situations'}</h1><p className="intro">{view==='queue'?'CoS reviews first. Then priority, with the oldest cases first.':'Pending or answered. One-offs stay here, even when they aren’t future rules.'}</p>{!(view==='queue'?queued:data.cases).length&&!loading&&<div className="empty"><Inbox size={26}/><h2>{view==='queue'?'Your queue is clear':'No submitted situations yet'}</h2><p>{view==='queue'?'Eligible cases will appear here. Unattended routing still needs connecting.':'Search for a situation, then escalate if you need a decision.'}</p></div>}
 {(view==='queue'?queued:[...data.cases].sort((a,b)=>b.createdAt-a.createdAt)).map(item=>{if(item.feedback)return <RuleFeedbackCase key={item.id} item={item} entries={data.entries} role={data.role} onSave={saveDecision}/>;const open=expandedCase===item.id;const precedent=data.entries.find(e=>e.id===item.precedentId);const review=item.answer?.role==='cos'&&!item.review;return <article className={`precedent-card case-card ${review&&view==='queue'?'needs-review':''}`} key={item.id}><div className="card-meta"><div className="inline-tags"><span className={`status-pill ${item.priority==='High'?'amber':''}`}>{item.priority}</span><span className={`status-pill ${item.answer?'':'amber'}`}>{item.answer?'Answered':'Pending'}</span>{review&&<span className="review-tag">CoS decided · Founder review</span>}</div><span>{item.answer?date(item.answer.at):age(item.createdAt)}</span></div><button className="card-toggle" aria-expanded={open} onClick={()=>setExpandedCase(open?null:item.id)}><h3>{item.situation}</h3><ChevronDown size={17}/></button><p className="muted">Submitted by {item.submitter} · {date(item.createdAt)}{item.routedAt?' · Routed to CoS':''}</p>{item.founderOnly&&<p className="notice amber">Founder-only · No one-hour resolution deadline or CoS fallback</p>}{open&&item.answer&&<><div className="rule-box"><h4>{item.answer.role==='cos'||!item.precedentId?'ONE-OFF — NOT A PRECEDENT':'RECORDED DECISION'}</h4><p>{item.answer.decision}</p></div><div className="card-columns"><div><h4>REASONING</h4><p>{item.answer.reasoning}</p></div><div><h4>EXCEPTION</h4><p>{item.answer.exception||'None recorded'}</p></div></div><p className="muted">Decided by {item.answer.role==='cos'?'CoS':'Founder'}. {item.review?`Founder review: ${item.review.outcome}.`:''}</p>{precedent&&<details className="linked-precedent"><summary>Open the founder-approved future precedent</summary><PrecedentCard entry={currentRule(data.entries,precedent.id)||precedent} entries={data.entries} expanded/></details>}</>}{view==='queue'&&!item.answer&&<Button onClick={()=>setDraft({kind:'answer',item})}>Record decision</Button>}{data.role==='founder'&&review&&<Button onClick={()=>setDraft({kind:'review',item})}>Review CoS decision</Button>}{data.role==='founder'&&item.answer&&!item.precedentId&&!review&&<Button variant="outline" onClick={()=>setDraft({kind:'promote',item})}>Make this a precedent</Button>}</article>;})}</>}
 {report&&<ReportRuleForm key={report.id} entry={report} onSave={saveReport} onClose={()=>setReport(null)}/>}
 {escalation&&<section className="edit-panel" aria-label="Escalate situation"><div className="section-heading"><h2>Ask for a decision</h2><Button disabled={saving} variant="ghost" onClick={()=>setEscalation(null)}>Close</Button></div><form className="fields" onSubmit={saveEscalation}><label>Situation<Textarea required value={escalation.text} onChange={e=>{setEscalation({...escalation,text:e.target.value});setPriority('');}}/></label><label>Submitted by<NativeSelect required value={submitter} onChange={e=>setSubmitter(e.target.value)}><NativeSelectOption value="">Choose your name</NativeSelectOption>{people.map(p=><NativeSelectOption key={p.name}>{p.name}</NativeSelectOption>)}</NativeSelect></label><p className="notice">AI priority suggestions are not connected. Please choose the priority yourself.</p>{founderOnly&&<p className="notice amber">This public-escalation policy requires High priority and a founder decision, without timed CoS backup.</p>}<label>Priority <small>(you must choose)</small><NativeSelect required value={priority} onChange={e=>setPriority(e.target.value)}><NativeSelectOption value="">Choose High, Medium or Low</NativeSelectOption>{['High','Medium','Low'].map(p=><NativeSelectOption key={p} disabled={founderOnly&&p!=='High'}>{p}</NativeSelectOption>)}</NativeSelect></label>{submitError&&<p role="alert" className="error">{submitError}</p>}<Button type="submit" disabled={saving}>{saving?'Saving…':submitError?'Retry':priority?`Submit as ${priority} priority`:'Choose a priority to submit'}</Button></form></section>}
 {draft&&<DecisionForm key={`${draft.kind}-${draft.item?.id||draft.entry?.id}`} draft={draft} role={data.role} entries={data.entries} onSave={saveDecision} onClose={()=>setDraft(null)}/>}
 <details className="demo-settings"><summary>Demo &amp; setup · Alerts and automatic routing are off</summary><p className="development-note">AI suggestions, email delivery and unattended one-hour routing are not connected. Do not use this demo for live customer cases.</p><RoutingDemo/></details>
 <footer><ShieldCheck size={15}/>Shared decisions. Human judgment.<span>{loading?'Connecting…':loadError?'Connection interrupted':<><Check size={13}/>{data.services?.storage==='convex'?'Convex connected':'Local database connected'}</>}</span></footer>
 </main></div>;
}
