import {isCommercialScopeCompatible} from './semantic-match.ts';

export type Category = 'Customer Service' | 'Operations' | 'Marketing';
export type Role = 'team' | 'founder' | 'cos';
export type Priority = 'High' | 'Medium' | 'Low';
export type Entry = {id:string;title:string;category:Category;situation:string;decision:string;reasoning:string;exception:string;status:'Active'|'Superseded'|'No rule';seed:boolean;createdAt:number;founderOnly?:boolean;supersedesId?:string;replacementId?:string;changeReason?:string;caseId?:string};
export type Answer = {decision:string;reasoning:string;exception:string;role:'founder'|'cos';at:number};
export type RuleFeedback = {outcome:string;source:Entry;resolution?:{choice:'keep'|'clarify'|'replace';reason:string;at:number;entryId:string}};
export type Situation = {id:string;situation:string;submitter:string;priority:Priority;founderOnly:boolean;sourceId?:string;feedback?:RuleFeedback;createdAt:number;routedAt?:number;answer?:Answer;review?:{outcome:'approved'|'amended'|'one-off';at:number};precedentId?:string;callFeedback?:{value:'yes'|'no'|'not_sure';note:string;at:number};actionIds:string[]};
export type Notice = {id:string;caseId:string;to:string;kind:'high'|'fallback'|'answer'|'decided';state:'pending'|'sent';createdAt:number};
export type ConditionUse={id:string;precedentId:string;conditionId:string;conditionLabel:string;decision:string;source:'real';createdAt:number};
export type State = {entries:Entry[];cases:Situation[];notices:Notice[];usage?:{precedentMatches:number;matchActionIds:string[]};conditionUses?:ConditionUse[]};
export const categories:Category[]=['Customer Service','Operations','Marketing'];

export class AppError extends Error {status:number; constructor(message:string,status=400){super(message);this.status=status;}}
export function currentRule(entries:Entry[],id:string):Entry|undefined{const seen=new Set<string>();let entry=entries.find(e=>e.id===id);while(entry?.status==='Superseded'&&entry.replacementId&&!seen.has(entry.id)){seen.add(entry.id);entry=entries.find(e=>e.id===entry!.replacementId);}return entry?.status==='Active'?entry:undefined;}
const stop=new Set('a an the and or to of for with without in on at is it its be been being has have had do does did says say customer customers product products order orders situation wants want asking asks ask already but this that there them they their i we can could should would after before from as by my me no not'.split(' '));
const aliases:Record<string,string>={perfume:'fragrance',perfumes:'fragrance',fragrances:'fragrance',broken:'damage',damaged:'damage',cracked:'damage',leaking:'damage',discounts:'discount',discounted:'discount',unboxing:'unbox',video:'video',videos:'video',addresses:'address',modification:'modify',modifications:'modify',change:'modify',changes:'modify',changed:'modify',packed:'pack',packing:'pack',warehouse:'warehouse',refund:'return',returned:'return',returns:'return',influencers:'influencer',collaborations:'collaboration',swapped:'swap',swapping:'swap',publicly:'public',threatens:'threat',threatening:'threat',threatened:'threat',negatively:'negative',reviews:'review',reviewed:'review',posted:'post',messages:'message',messaging:'message',stones:'stone',used:'use',opened:'open'};
export function tokens(text:string){return [...new Set((text.toLowerCase().match(/[\p{L}\p{N}]+/gu)||[]).filter(w=>!stop.has(w)).map(w=>aliases[w]||w))];}
export function search(entries:Entry[],query:string){const active=entries.filter(e=>e.status==='Active'&&isCommercialScopeCompatible(query,`${e.title} ${e.situation}`));const q=tokens(query);if(!q.length)return [];const docs=active.map(e=>tokens(e.situation));return active.map((entry,i)=>{const shared=q.filter(w=>docs[i].includes(w));const weight=(w:string)=>1+Math.log((active.length+1)/(1+docs.filter(d=>d.includes(w)).length));const matched=shared.reduce((n,w)=>n+weight(w),0);const total=q.reduce((n,w)=>n+weight(w),0);const score=matched/Math.max(total,1);return {entry,score,possible:score<.66};}).filter(x=>x.score>=.18).sort((a,b)=>b.score-a.score||a.entry.id.localeCompare(b.entry.id)).slice(0,3);}
export function publicRisk(text:string){return /\b(?:negative|bad)\s+(?:review|post)|\breputation\b|\b(?:threat\w*|escalat\w*|complain\w*)\b[\s\S]*\b(?:public\w*|social media|viral)\b|\b(?:public\w*|social media)\b[\s\S]*\b(?:threat\w*|escalat\w*|complain\w*|negative)\b/i.test(text);}
export function queue(cases:Situation[],role:Role){return cases.filter(c=>role==='cos'?!!c.routedAt&&!c.founderOnly&&!c.answer:!c.answer||(c.answer.role==='cos'&&!c.review)).sort((a,b)=>{const review=(c:Situation)=>c.answer?.role==='cos'&&!c.review?0:1;return review(a)-review(b)||(['High','Medium','Low'].indexOf(a.priority)-['High','Medium','Low'].indexOf(b.priority))||a.createdAt-b.createdAt;});}
