import type {Category} from './domain';
import {discountConditionRows} from './demo-discount.ts';

// DEMO DATA ONLY. Invented people, references and recent dates; one entry per supplied policy.
export const demoEntries = [
 {id:'fictional-policy-01',title:'Additional customer discount',category:'Customer Service' as Category,situation:'On 17 August 2026, fictional customer Rhea Vale (order DEMO-1001) asks for an additional discount beyond the current promotion.',decision:'The additional discount depends on how many orders the customer has.',reasoning:'First-time customers already receive the standard acquisition offer. A customer with 10+ orders has demonstrated loyalty, so a reciprocal discount is justified while remaining rare.',exception:'If none of the listed situations fit, ask the founder.',conditionRows:discountConditionRows,status:'Active' as const},
 {id:'fictional-policy-02',title:'Damaged product without an unboxing video',category:'Customer Service' as Category,situation:'On 18 August 2026, fictional customer Dev Rowan reports that order DEMO-1002 arrived damaged, but they have no unboxing video.',decision:"Check the customer's photos, the packaging team's records or images, order and complaint history, and whether the product was securely packed.",reasoning:'Establish whether the damage happened in transit or during packing before deciding responsibility.',exception:"If the product was not securely packed, treat it as company fault and offer a replacement or refund.",status:'Active' as const},
 {id:'fictional-policy-03',title:"Opened fragrance doesn't suit the customer",category:'Customer Service' as Category,situation:'On 19 August 2026, fictional customer Isha Wren says the opened fragrance from order DEMO-1003 does not suit them.',decision:'Opened products are normally not eligible for return.',reasoning:'Usage, condition, order history and similar complaints can justify an exception to the normal no-return rule.',exception:'If it was used slightly and the customer has good history, allow the return. If it was used slightly and the customer has poor history, deny the return. If it was used moderately and the customer has very good history, offer a replacement. If it was used heavily and the customer has poor history, deny the return. If none of these situations fit, ask the founder.',status:'Active' as const},
 {id:'fictional-policy-04',title:'Offline warehouse discount',category:'Customer Service' as Category,situation:'On 20 August 2026, fictional customer Kabir Moss visits the warehouse for quote DEMO-1004, checks the products and asks for a discount.',decision:'Below ₹1,000 → 5%. ₹1,000–₹8,000 → 10%. Orders above ₹5,000 → 1–2 complimentary samples.',reasoning:'Not specified in the policy draft.',exception:'Above ₹8,000 requires founder approval.',status:'Active' as const},
 {id:'fictional-policy-05',title:'Reverse parcel contains stones instead of the product',category:'Customer Service' as Category,situation:'On 21 August 2026, fictional customer Meera Flint hands the correct product to the pickup agent for return DEMO-1005, but the reverse parcel later arrives containing stones and the logistics team does not respond.',decision:"Check the customer's pickup photo or video, check CCTV if available, raise the case with logistics, allow logistics 48 hours, and keep the customer informed with evidence of the escalation.",reasoning:"The customer should not be left without a resolution indefinitely because a logistics partner is not responding.",exception:'Valid customer proof → refund or replace immediately, based on their preference. Still unresolved after 48 hours → refund or replace and escalate the logistics matter to legal with a summary.',status:'Active' as const},
 {id:'fictional-policy-07',title:'Customer threatens or escalates publicly',category:'Customer Service' as Category,situation:'On 22 August 2026, fictional customer Noor Lake says they will post publicly about complaint DEMO-1007.',decision:'Give the case special attention and escalate it for founder involvement.',reasoning:'A potential public or reputation escalation makes this different from an ordinary support case.',exception:'Founder involvement is always required.',status:'Active' as const,founderOnly:true},
 {id:'fictional-policy-08',title:'Website stock is physically unavailable',category:'Customer Service' as Category,situation:'On 23 August 2026, fictional customer Tara Bloom buys order DEMO-1008 while the website shows stock that is not physically available.',decision:'Contact the customer and offer either an alternative product or order cancellation.',reasoning:'Not specified in the policy draft.',exception:'No escalation is required.',status:'Active' as const},
 {id:'fictional-policy-09',title:'Last unit: offline versus online customer',category:'Customer Service' as Category,situation:'On 24 August 2026, fictional customer Omar Pine is at the warehouse for the final unit while fictional online customer Lina Shore has already bought it in order DEMO-1009.',decision:'If the offline customer is buying several products, say this item sold out and preserve the online order. If they came specifically for this product, it may be given to them and the online order cancelled.',reasoning:'This is contextual rather than a rigid online-first or offline-first rule.',exception:'Either customer’s order history can change who is prioritised.',status:'Active' as const},
 {id:'fictional-policy-10',title:'Bulk request for tools',category:'Customer Service' as Category,situation:'On 25 August 2026, fictional customer Ayan Reed asks to buy tools in bulk under request DEMO-1010, although those tools are not normally sold separately.',decision:'Normally deny the request.',reasoning:'Not specified in the policy draft.',exception:'An exception can be made for a regular or high-value customer.',status:'Active' as const},
 {id:'fictional-policy-11',title:'Monday leave',category:'Operations' as Category,situation:'On 26 August 2026, fictional employee Sana Vale submits leave request DEMO-1011 for a Monday.',decision:'Normally do not approve Monday leave.',reasoning:'Sunday is non-working, so work accumulates for Monday.',exception:'Monday leave can be approved if the employee has covered additional or non-working days to support the team.',status:'Active' as const},
 {id:'fictional-policy-12a',title:'Order modification after packing — previous rule',category:'Operations' as Category,situation:'On 27 August 2026, fictional customer Aria Cloud asks to modify packed order DEMO-1012.',decision:'Do not allow the change because modifying a physically packed order and its system record creates difficulty.',reasoning:'Not specified in the policy draft.',exception:'This rule has been replaced by the current address-change rule.',status:'Superseded' as const,replacementId:'fictional-policy-12b'},
 {id:'fictional-policy-12b',title:'Address change after packing — current rule',category:'Operations' as Category,situation:'On 28 August 2026, fictional customer Aria Cloud asks to change the address on packed order DEMO-1013.',decision:"Allow address changes. Orders may be packed, but do not print the label or mark them dispatched until 12pm. After 12pm, hold the order and tell the customer it will be delayed.",reasoning:'A short hold is better than delivering to an incorrect checkout address and causing a return-to-origin.',exception:'For an urgent or occasion-related order, make the extra effort to accommodate the change.',status:'Active' as const,supersedesId:'fictional-policy-12a',changeReason:'Incorrect or default checkout addresses made a short operational hold safer than a later return-to-origin.'},
 {id:'fictional-policy-13',title:'College brand sponsorship request',category:'Marketing' as Category,situation:'On 29 August 2026, fictional Northstar College requests sponsorship DEMO-1013 for its annual fest, offering posts, reels, stories and a student business challenge.',decision:'Approve when the student audience overlaps the urban 22–35 target, the request is within ₹40,000, and expected reach is at least 2,000 students or equivalent social amplification.',reasoning:'Judge awareness value through audience fit and reach per rupee, rather than immediate sales.',exception:'Strong proven online amplification or a useful real-brand MBA challenge can justify approval above ₹40,000. Otherwise, asks above ₹40,000 or unclear audience fit require founder escalation.',status:'Active' as const},
 {id:'fictional-policy-14',title:'Paid influencer collaboration',category:'Marketing' as Category,situation:'On 30 August 2026, fictional creator Zoya Fern says collaboration DEMO-1014 must be paid.',decision:'Ask for commercials. Standard budget: ₹3,000 for a reel and story. Explain the preference for long-term partnerships with selected creators.',reasoning:'Prefer repeated work with a smaller group of creators over expensive one-off collaborations.',exception:'Negotiate up to ₹4,000 maximum. Decline above ₹4,000.',status:'Active' as const},
];

// The supplied no-rule example is deliberately not approved knowledge.
export const demoUnmatchedScenario={customer:'Fictional customer Elio Hart',orderId:'DEMO-1006',date:'31 August 2026',situation:'Two orders were swapped and one has reached the final delivery station. Should it be returned to origin, or delivered and collected afterward?'} as const;

export function publicSnapshot(){return {mode:'demo',role:'team',entries:demoEntries,cases:[],readOnly:true};}
export function isNormalRecord(record:unknown){return !/MIGRATION TEST ONLY|DEMO TEST ONLY/i.test(JSON.stringify(record));}
