import type { Entry } from './domain';

const seed = (id: string, title: string, category: Entry['category'], situation: string, decision: string, reasoning = '', exception = '', extra: Partial<Entry> = {}): Entry => ({id,title,category,situation,decision,reasoning,exception,status:'Active',seed:true,createdAt:0,...extra});
export const seedEntries: Entry[] = [
  seed('1','Additional customer discount','Customer Service','A customer is asking for an additional discount beyond the existing promotion.','First-time customer → no additional discount. Customer with 10+ orders → additional discount can be offered.','First-time customers already receive the best acquisition offer through the standard promotion, so stacking a further discount erodes margin without proven loyalty. A customer with 10+ orders has demonstrated real lifetime value, so a modest reciprocal discount protects retention at a justifiable cost — keeping the bar high keeps it rare enough that it never becomes an expected default.','10+ orders.',{customerType:'direct'}),
  seed('2','Damaged product without unboxing video','Customer Service','Customer says the product arrived damaged but has no unboxing video.',"Check customer photos, packaging team's records/images, customer's order/complaint history, and whether the product was securely packed.",'Need to establish whether the damage happened in transit or was a packaging issue before deciding fault.',"If the product wasn't securely packed → company fault → offer replacement/refund."),
  seed('3',"Opened fragrance doesn't suit customer",'Customer Service',"Customer opened and used the fragrance but says it doesn't suit them.",'Opened products are normally not eligible for return.','Extent of usage and customer order history can justify an exception to the normal no-return rule; also check if other customers reported the same issue with this product.','Slightly used + good condition + good history → return exception possible. Moderately used + very good history → offer replacement. Heavily used + poor history → deny.'),
  seed('4','Offline warehouse discount','Customer Service','Customer visits the warehouse, checks the product in person, and wants a discount.','Below ₹1,000 → 5%. ₹1,000–₹8,000 → 10%. Orders above ₹5,000 → 1–2 complimentary samples.','','Above ₹8,000 → founder approval required.'),
  seed('5','Returned package has stones instead of product','Customer Service',"Customer returned the correct product, but the package that arrives back contains stones/no product, and logistics isn't responding.","Check the customer's pickup photo/video, check CCTV if available, raise with logistics, give logistics 48 hours, keep the customer informed with evidence of the escalation.","The customer shouldn't be left without resolution indefinitely because a logistics partner isn't responding.",'If the customer has valid proof → refund/replacement per their preference, immediately. If unresolved after the 48-hour window → refund/replacement anyway, and escalate the logistics matter to legal with a summary.'),
  seed('6','Swapped orders','Customer Service','Two orders were mistakenly swapped and one has already reached the final delivery station — RTO it, or let it deliver and arrange the return after?','No defined rule yet.','','',{status:'No rule'}),
  seed('7','Customer threatens/escalates publicly','Customer Service',"Customer says they'll escalate publicly, already have, or have posted/reviewed negatively somewhere.",'Give the case special attention.','Potential reputation/public escalation makes this different from a normal support case.','',{founderOnly:true}),
  seed('8','Website shows available but physically unavailable','Customer Service',"A product shows as available online due to a stock sync issue, but isn't actually in stock.",'Contact the customer and offer either a replacement/alternative product or order cancellation.'),
  seed('9','Last quantity — offline vs online customer','Customer Service','Only one unit remains; an offline customer is at the warehouse while an online customer has already purchased it.',"If the offline customer is buying multiple products → tell them this one sold out, preserve the online order. If the offline customer came specifically for this product → may give it to them and cancel the online order.",'This is contextual, not a rigid online-first/offline-first rule.','Customer order history on either side can shift which customer is prioritized.'),
  seed('10','Bulk request for tools','Customer Service',"A customer wants to buy tools in bulk that aren't normally sold separately.",'Normally deny the request.','','If the customer is a regular/high-value customer → exception can be made.'),
  seed('11','Monday leave','Operations','An employee asks for leave on Monday.','Normally not approved.','Sunday is non-working, so work piles up on Monday — the rule exists because of workload.','If the employee has covered additional/non-working days to support the team, Monday leave can be approved.'),
  seed('12a','Order modification after packing — previous rule','Operations',"Customer wants to modify an order after it's been packed.",'Not allowed — changing a physically packed order and the system record creates difficulty.','','',{status:'Superseded',replacementId:'12b'}),
  seed('12b','Address changes after packing — current rule','Operations','Customer wants to change the delivery address after the order has been packed.',"Address modifications are allowed. Orders can still be packed, but don't print the label or mark dispatched until 12pm. If a modification comes in after 12pm, hold the order and tell the customer it'll be delayed.",'Addresses are sometimes selected incorrectly or defaulted at checkout — delivering to the wrong address and eating an RTO later is worse than a short hold.','If urgent or occasion-related, make the extra effort to accommodate despite the added work.',{supersedesId:'12a',changeReason:'Addresses are sometimes selected incorrectly or defaulted at checkout — delivering to the wrong address and eating an RTO later is worse than a short hold.'}),
  seed('13','WhatsApp launch message','Marketing','What to keep in mind drafting a WhatsApp message for a product/discovery-set launch.','First line should be hook-worthy. Keep the message concise, not unnecessarily lengthy.','WhatsApp is a personal, interruptive channel — people decide whether to keep reading within the first line or notification preview, and a message that reads as a mass promo rather than something worth their attention increases opt-outs, which are expensive to earn back.'),
  seed('14','Paid influencer collaboration','Marketing','An influencer says they only do paid collaborations.','Ask for commercials. Standard budget: ₹3,000 for a reel + story. Communicate preference for long-term partnerships with selected creators.','Prefer working repeatedly with a smaller group of creators rather than paying high amounts for one-off collaborations.','Can negotiate up to ₹4,000 maximum. Above ₹4,000 → decline.'),
];
